FROM node:alpine as build
WORKDIR /app/client
COPY client/package*.json ./
RUN npm install
COPY ./client .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/client/.next /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
