# Use an official Node.js runtime as a base image
FROM node:alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY server/package*.json ./

# Install the application dependencies
RUN npm install

# Copy the server folder into the container
COPY  ./server .

# Expose the port your app runs on
EXPOSE 8000

# Command to run your application
CMD ["npm", "start"]